<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Required fields are marked with an a_d84d8d</name>
   <tag></tag>
   <elementGuidId>3984e156-e96c-489f-aa3c-6d9f60077ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='hs-form-iframe-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hs-form-iframe-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a36cfbf7-a637-49f9-80a5-26a9a37c5234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hs-form-iframe-0</value>
      <webElementGuid>87404ef8-d4b2-48ef-be9e-fe760ad91a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hs-form-iframe</value>
      <webElementGuid>aef8db4e-46b8-4577-a200-cbd2dd51c878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Form 0</value>
      <webElementGuid>1158529a-fbcb-40c7-84d9-fea4db37ea3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fcf7b31b-73ce-4f2a-9854-4b155f753460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>498283ca-2cfa-4c3c-aac4-95aea4795330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1068</value>
      <webElementGuid>ff3d3b8c-7eec-4e11-9261-6f9782eeb8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs-form-iframe-0&quot;)</value>
      <webElementGuid>96432d60-0b2e-45db-b43e-9950095ea49f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='hs-form-iframe-0']</value>
      <webElementGuid>5d074b8f-e06c-4f08-9f06-f7e636414d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hbspt-form-fb79b9fc-d2fd-49c8-8fcc-1d62a68be655']/iframe</value>
      <webElementGuid>300628b1-4c35-4c92-b7bc-a3cc2d2147c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a4f077f2-253b-49b7-8aa7-e4b7d69edc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'hs-form-iframe-0' and @title = 'Form 0']</value>
      <webElementGuid>5fa31efd-3749-4e54-81f4-5cb77c283dd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
